const books = [
  { id: 1, title: "The Year of Magical Thinking", author: "Joan Didion", genre: "memoir", mood: ["grief", "loss", "death", "healing"], description: "A profound, honest account of grief after the sudden death of her husband.", summary: "After the sudden death of her husband, Joan Didion spent a year lost in the fog of grief. A raw, unflinching examination of how we grieve and how we go on.", themes: ["Grief", "Marriage", "Loss", "Memory", "Survival"], music: "Max Richter - On the Nature of Daylight", music_genre: "literary", cover_color: "#6B7280", year: 2005, pages: 227, reading_time: "5-6 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 2, title: "A Grief Observed", author: "C.S. Lewis", genre: "memoir", mood: ["grief", "faith", "loss", "spirituality"], description: "Raw journals written after his wife's death. Searingly honest and ultimately hopeful.", summary: "Written after his wife's death, C.S. Lewis confronts the silence of God, the unreality of death, and the terrifying absence of someone beloved.", themes: ["Grief", "Faith", "Loss", "Love", "God"], music: "Samuel Barber - Adagio for Strings", music_genre: "literary", cover_color: "#78716C", year: 1961, pages: 76, reading_time: "2-3 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 3, title: "When Breath Becomes Air", author: "Paul Kalanithi", genre: "memoir", mood: ["mortality", "meaning", "grief", "hope", "purpose"], description: "A neurosurgeon faces terminal cancer and asks: what makes a life worth living?", summary: "Paul Kalanithi was diagnosed with stage IV lung cancer at 36. This memoir is a meditation on what makes life meaningful. Beautiful, devastating, and ultimately life-affirming.", themes: ["Mortality", "Medicine", "Meaning", "Identity", "Love"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "poetry", cover_color: "#4A90D9", year: 2016, pages: 228, reading_time: "5-6 hours", rating: 4.9, difficulty: "moderate", language: "English" },
  { id: 4, title: "The Power of Now", author: "Eckhart Tolle", genre: "self-help", mood: ["anxiety", "stress", "overthinking", "peace", "mindfulness"], description: "A spiritual guide to escaping the anxious mind and finding presence.", summary: "Eckhart Tolle teaches that most suffering comes from being trapped in the past or future. Practical spiritual exercises to quiet the thinking mind and access present-moment peace.", themes: ["Mindfulness", "Presence", "Consciousness", "Peace"], music: "Brian Eno - Music for Airports", music_genre: "scifi", cover_color: "#6EE7B7", year: 1997, pages: 236, reading_time: "6-8 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 5, title: "Wherever You Go, There You Are", author: "Jon Kabat-Zinn", genre: "self-help", mood: ["anxiety", "mindfulness", "stress", "calm", "peace"], description: "Simple, accessible mindfulness practices for everyday life.", summary: "Jon Kabat-Zinn offers a gentle guide to bringing mindfulness into everyday life. Short chapters, immediately practical.", themes: ["Mindfulness", "Meditation", "Acceptance", "Presence"], music: "Debussy - Clair de Lune", music_genre: "literary", cover_color: "#93C5FD", year: 1994, pages: 163, reading_time: "4-5 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 6, title: "First, We Make the Beast Beautiful", author: "Sarah Wilson", genre: "memoir", mood: ["anxiety", "self-discovery", "mental health", "healing"], description: "An intimate look at living with and even befriending anxiety.", summary: "Sarah Wilson spent 20 years battling anxiety before deciding to write about it as something to befriend. Weaves personal story with neuroscience and practical wisdom.", themes: ["Anxiety", "Mental Health", "Self-compassion", "Healing"], music: "Nils Frahm - Says", music_genre: "poetry", cover_color: "#C084FC", year: 2017, pages: 304, reading_time: "7-8 hours", rating: 4.4, difficulty: "moderate", language: "English" },
  { id: 7, title: "Braving the Wilderness", author: "Brene Brown", genre: "self-help", mood: ["loneliness", "belonging", "connection", "courage"], description: "A call to true belonging — not fitting in, but showing up as yourself.", summary: "Brene Brown's research shows that true belonging doesn't require you to change who you are. A call to courage for anyone who has felt they don't belong.", themes: ["Belonging", "Courage", "Connection", "Vulnerability"], music: "Sufjan Stevens - Death With Dignity", music_genre: "memoir", cover_color: "#FCA5A5", year: 2017, pages: 192, reading_time: "5-6 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 8, title: "The Alchemist", author: "Paulo Coelho", genre: "fiction", mood: ["purpose", "loneliness", "journey", "hope", "destiny"], description: "A fable about following your heart and finding your personal legend.", summary: "A young shepherd sets off across the desert to find treasure and discovers the universe conspires to help those who pursue their Personal Legend.", themes: ["Purpose", "Journey", "Destiny", "Love", "Soul"], music: "Rodrigo y Gabriela - Tamacun", music_genre: "selfhelp", cover_color: "#FDE68A", year: 1988, pages: 208, reading_time: "3-4 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 9, title: "Eleanor Oliphant is Completely Fine", author: "Gail Honeyman", genre: "fiction", mood: ["loneliness", "healing", "connection", "resilience", "trauma"], description: "A deeply moving story about isolation, trauma, and the power of kindness.", summary: "Eleanor Oliphant has a very tidy life and is hiding tremendous pain. When she befriends a kind IT technician, cracks appear in her armor. About profound loneliness and the power of unexpected kindness.", themes: ["Loneliness", "Trauma", "Kindness", "Healing", "Connection"], music: "Nick Drake - Northern Sky", music_genre: "memoir", cover_color: "#A78BFA", year: 2017, pages: 384, reading_time: "9-10 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 10, title: "Man's Search for Meaning", author: "Viktor Frankl", genre: "memoir", mood: ["resilience", "purpose", "suffering", "hope", "meaning"], description: "A psychiatrist's account of surviving the Holocaust and finding meaning in suffering.", summary: "Viktor Frankl survived Auschwitz and developed logotherapy — the theory that the primary human drive is the pursuit of meaning. Even in the darkest circumstances, we retain the freedom to choose our attitude.", themes: ["Meaning", "Resilience", "Survival", "Hope", "Freedom"], music: "Bach - Cello Suite No. 1", music_genre: "historical", cover_color: "#6B7280", year: 1946, pages: 200, reading_time: "4-5 hours", rating: 4.9, difficulty: "moderate", language: "English" },
  { id: 11, title: "The Book of Joy", author: "Dalai Lama and Desmond Tutu", genre: "non-fiction", mood: ["joy", "resilience", "gratitude", "adversity", "spirituality"], description: "Two spiritual leaders on finding joy despite suffering.", summary: "For five days the Dalai Lama and Archbishop Tutu discussed how to find joy in a world full of suffering. Luminous, funny, and deeply practical.", themes: ["Joy", "Suffering", "Gratitude", "Friendship", "Compassion"], music: "Mozart - Piano Concerto No. 21", music_genre: "romance", cover_color: "#FCD34D", year: 2016, pages: 368, reading_time: "8-9 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 12, title: "Untamed", author: "Glennon Doyle", genre: "memoir", mood: ["courage", "resilience", "self-discovery", "freedom", "identity"], description: "A fiercely honest memoir about breaking free from expectations.", summary: "Glennon Doyle discovers that the life she had built was a cage. Breaking free from expectation is the bravest and most necessary act. Raw, funny, revolutionary.", themes: ["Freedom", "Identity", "Courage", "Love", "Authenticity"], music: "Lizzo - Good as Hell", music_genre: "selfhelp", cover_color: "#F472B6", year: 2020, pages: 352, reading_time: "8-9 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 13, title: "The Bell Jar", author: "Sylvia Plath", genre: "fiction", mood: ["depression", "identity", "mental health", "survival"], description: "A classic semi-autobiographical novel about mental breakdown and recovery.", summary: "Esther Greenwood descends into a darkness she cannot name. Plath's only novel is darkly funny and terrifyingly honest about mental illness.", themes: ["Depression", "Identity", "Mental Health", "Society", "Recovery"], music: "Nick Drake - Pink Moon", music_genre: "mystery", cover_color: "#374151", year: 1963, pages: 244, reading_time: "6-7 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 14, title: "Darkness Visible", author: "William Styron", genre: "memoir", mood: ["depression", "mental health", "survival", "understanding"], description: "An unflinching memoir of major depression — validating and ultimately hopeful.", summary: "Widely considered the best description of clinical depression ever written. Styron insists on the biological reality of the illness while illuminating its emotional horror.", themes: ["Depression", "Mental Illness", "Survival", "Understanding"], music: "Arvo Part - Fratres", music_genre: "literary", cover_color: "#1F2937", year: 1990, pages: 112, reading_time: "2-3 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 15, title: "Reasons to Stay Alive", author: "Matt Haig", genre: "memoir", mood: ["depression", "anxiety", "hope", "mental health", "healing"], description: "A warm, honest account of living with depression and finding reasons to stay.", summary: "Matt Haig's honest, warm, occasionally funny account of how he survived depression. An antidote to despair that has helped millions feel less alone.", themes: ["Depression", "Anxiety", "Recovery", "Hope", "Life"], music: "Coldplay - Yellow", music_genre: "selfhelp", cover_color: "#6EE7B7", year: 2015, pages: 288, reading_time: "5-6 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 16, title: "The Little Prince", author: "Antoine de Saint-Exupery", genre: "fiction", mood: ["wonder", "joy", "childhood", "love", "loss"], description: "A timeless fable about love, loss, and seeing with the heart.", summary: "A little prince falls to Earth from his tiny planet. What follows is a series of visits to strange planets, each inhabited by a lonely adult who has forgotten what matters.", themes: ["Love", "Wonder", "Innocence", "Loss", "Friendship"], music: "Yann Tiersen - Comptine d un autre ete", music_genre: "romance", cover_color: "#FDE68A", year: 1943, pages: 96, reading_time: "2-3 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 17, title: "Big Magic", author: "Elizabeth Gilbert", genre: "self-help", mood: ["creativity", "joy", "purpose", "inspiration", "courage"], description: "A joyful invitation to live a creative life, fear and all.", summary: "Elizabeth Gilbert believes creativity is a relationship between you and ideas that want to be expressed. An energizing, permission-giving book for anyone with a creative life waiting to be lived.", themes: ["Creativity", "Inspiration", "Courage", "Purpose", "Art"], music: "Norah Jones - Come Away With Me", music_genre: "selfhelp", cover_color: "#A78BFA", year: 2015, pages: 288, reading_time: "6-7 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 18, title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", genre: "fiction", mood: ["humor", "wonder", "escape", "joy", "adventure"], description: "Absurdist comedy that makes the universe feel like a delightful adventure.", summary: "Arthur Dent is whisked off Earth moments before its demolition. What follows is the most delightfully absurd adventure in the universe.", themes: ["Humor", "Adventure", "Absurdity", "Friendship", "Meaning"], music: "Daft Punk - Something About Us", music_genre: "scifi", cover_color: "#34D399", year: 1979, pages: 224, reading_time: "5-6 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 19, title: "Educated", author: "Tara Westover", genre: "memoir", mood: ["identity", "trauma", "self-discovery", "resilience", "family"], description: "A woman who grew up outside the education system discovers who she is.", summary: "Tara Westover grew up in rural Idaho, never setting foot in a classroom until age 17. She went on to get a PhD from Cambridge. Extraordinary and haunting.", themes: ["Education", "Family", "Identity", "Trauma", "Self-creation"], music: "Bon Iver - Skinny Love", music_genre: "memoir", cover_color: "#D97706", year: 2018, pages: 352, reading_time: "9-10 hours", rating: 4.9, difficulty: "moderate", language: "English" },
  { id: 20, title: "The Gifts of Imperfection", author: "Brene Brown", genre: "self-help", mood: ["self-worth", "shame", "identity", "courage", "wholehearted living"], description: "A guide to letting go of who you think you should be.", summary: "Brene Brown offers ten guideposts for living with authenticity — cultivating self-compassion, gratitude, creativity, and the courage to be imperfect.", themes: ["Self-worth", "Shame", "Authenticity", "Courage"], music: "Jason Mraz - I'm Yours", music_genre: "selfhelp", cover_color: "#F472B6", year: 2010, pages: 160, reading_time: "4-5 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 21, title: "Know My Name", author: "Chanel Miller", genre: "memoir", mood: ["trauma", "healing", "identity", "resilience", "courage"], description: "A survivor's powerful reclamation of identity and voice.", summary: "Chanel Miller was known only as Emily Doe. Know My Name is her reclamation of identity. Her writing is luminous. Her story is important.", themes: ["Trauma", "Healing", "Justice", "Identity", "Courage"], music: "Sufjan Stevens - Death With Dignity", music_genre: "memoir", cover_color: "#FCA5A5", year: 2019, pages: 368, reading_time: "9-10 hours", rating: 4.9, difficulty: "moderate", language: "English" },
  { id: 22, title: "When Things Fall Apart", author: "Pema Chodron", genre: "spiritual", mood: ["fear", "difficulty", "peace", "acceptance", "anxiety"], description: "Buddhist wisdom for the darkest moments.", summary: "Pema Chodron teaches that the only way through is to stop running. Instead of escaping our pain, we can meet it with curiosity and gentleness.", themes: ["Buddhism", "Impermanence", "Fear", "Compassion", "Acceptance"], music: "Chopin - Nocturne in E-flat major", music_genre: "romance", cover_color: "#6EE7B7", year: 1997, pages: 162, reading_time: "4-5 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 23, title: "The Prophet", author: "Kahlil Gibran", genre: "poetry", mood: ["wisdom", "love", "peace", "spirituality", "beauty"], description: "Timeless poetry-prose on love, children, work, sorrow.", summary: "A fictional prophet speaks on love, marriage, children, work, joy, sorrow, beauty, and death. Lyrical prose-poems of universal wisdom.", themes: ["Wisdom", "Love", "Life", "Spirituality", "Poetry"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "poetry", cover_color: "#D97706", year: 1923, pages: 96, reading_time: "2-3 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 24, title: "Tao Te Ching", author: "Lao Tzu", genre: "spiritual", mood: ["peace", "wisdom", "acceptance", "simplicity", "calm"], description: "81 short verses on the nature of existence.", summary: "Written 2500 years ago. 81 brief paradoxical verses about the nature of existence. A book to return to across a lifetime.", themes: ["Wisdom", "Philosophy", "Simplicity", "Nature", "Peace"], music: "Brian Eno - 1/1", music_genre: "poetry", cover_color: "#78716C", year: 400, pages: 112, reading_time: "2-3 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 25, title: "The Anxiety and Worry Workbook", author: "Clark and Beck", genre: "self-help", mood: ["anxiety", "worry", "stress", "practical", "healing"], description: "A science-backed CBT workbook to understand and overcome anxiety.", summary: "Based on decades of cognitive behavioral therapy research, this workbook guides readers through understanding their anxiety and developing concrete tools to manage it.", themes: ["Anxiety", "CBT", "Practical Tools", "Mental Health"], music: "Brian Eno - Music for Airports", music_genre: "default", cover_color: "#BAE6FD", year: 2010, pages: 336, reading_time: "8-10 hours", rating: 4.3, difficulty: "moderate", language: "English" },
  { id: 26, title: "Lost Connections", author: "Johann Hari", genre: "non-fiction", mood: ["loneliness", "depression", "connection", "society", "healing"], description: "A radical rethinking of depression as disconnection.", summary: "Johann Hari shows that depression and anxiety are largely caused by disconnection from meaningful work, other people, and the natural world. A compassionate call to reconnect.", themes: ["Depression", "Society", "Connection", "Meaning", "Healing"], music: "Nick Drake - Pink Moon", music_genre: "memoir", cover_color: "#6B7280", year: 2018, pages: 336, reading_time: "8-9 hours", rating: 4.4, difficulty: "moderate", language: "English" },
  { id: 27, title: "Option B", author: "Sheryl Sandberg and Adam Grant", genre: "non-fiction", mood: ["resilience", "grief", "hope", "recovery", "strength"], description: "How to build resilience when option A is no longer available.", summary: "After the sudden death of her husband, Sheryl Sandberg and Adam Grant explore how to rebuild joy and meaning after loss.", themes: ["Resilience", "Grief", "Recovery", "Strength", "Hope"], music: "Coldplay - The Scientist", music_genre: "selfhelp", cover_color: "#93C5FD", year: 2017, pages: 240, reading_time: "5-6 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 28, title: "The Noonday Demon", author: "Andrew Solomon", genre: "non-fiction", mood: ["depression", "mental health", "understanding", "healing"], description: "The most comprehensive and humane book ever written about depression.", summary: "Andrew Solomon spent a decade interviewing hundreds of people about depression. Winner of the National Book Award. Essential reading for anyone touched by this illness.", themes: ["Depression", "Mental Health", "Society", "Treatment"], music: "Samuel Barber - Adagio for Strings", music_genre: "literary", cover_color: "#374151", year: 2001, pages: 569, reading_time: "15-18 hours", rating: 4.7, difficulty: "challenging", language: "English" },
  { id: 29, title: "Braiding Sweetgrass", author: "Robin Wall Kimmerer", genre: "non-fiction", mood: ["wonder", "nature", "gratitude", "healing", "belonging"], description: "A botanist weaves indigenous wisdom with Western science.", summary: "Robin Wall Kimmerer weaves together indigenous plant knowledge, scientific ecology, and personal narrative. A book that will change how you see a forest.", themes: ["Nature", "Gratitude", "Indigenous Wisdom", "Ecology", "Belonging"], music: "Brian Eno - 1/1", music_genre: "default", cover_color: "#6EE7B7", year: 2013, pages: 390, reading_time: "9-11 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 30, title: "Between the World and Me", author: "Ta-Nehisi Coates", genre: "non-fiction", mood: ["identity", "justice", "fear", "history", "courage"], description: "A letter to his son about the reality of being Black in America.", summary: "Ta-Nehisi Coates writes with searing honesty about race, power, and the American Dream. Winner of the National Book Award.", themes: ["Race", "Identity", "Justice", "History", "Fear"], music: "Kendrick Lamar - Alright", music_genre: "literary", cover_color: "#1F2937", year: 2015, pages: 152, reading_time: "3-4 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 31, title: "The Untethered Soul", author: "Michael A. Singer", genre: "spiritual", mood: ["peace", "freedom", "consciousness", "healing", "awareness"], description: "A journey beyond yourself to discover who you really are.", summary: "Michael Singer teaches how to observe your inner experience without being consumed by it and how to open your heart unconditionally.", themes: ["Consciousness", "Freedom", "Awareness", "Spirituality", "Peace"], music: "Max Richter - On the Nature of Daylight", music_genre: "poetry", cover_color: "#93C5FD", year: 2007, pages: 200, reading_time: "5-6 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 32, title: "The Five Love Languages", author: "Gary Chapman", genre: "self-help", mood: ["love", "relationships", "connection", "communication", "healing"], description: "Learn to speak your partner's love language.", summary: "Gary Chapman argues that every person expresses and receives love in one of five ways. Understanding this has transformed millions of relationships.", themes: ["Love", "Communication", "Relationships", "Understanding"], music: "Norah Jones - Come Away With Me", music_genre: "romance", cover_color: "#F472B6", year: 1992, pages: 208, reading_time: "5-6 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 33, title: "Attached", author: "Amir Levine and Rachel Heller", genre: "non-fiction", mood: ["love", "relationships", "anxiety", "healing", "self-discovery"], description: "How attachment theory can transform your understanding of love.", summary: "Drawing on attachment research, this book explains why some people are secure in relationships while others are anxious or avoidant.", themes: ["Attachment", "Relationships", "Psychology", "Love", "Healing"], music: "Chopin - Nocturne in E-flat major", music_genre: "romance", cover_color: "#FCA5A5", year: 2010, pages: 294, reading_time: "7-8 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 34, title: "Start With Why", author: "Simon Sinek", genre: "non-fiction", mood: ["purpose", "inspiration", "meaning", "motivation", "leadership"], description: "Why some people and organisations are more innovative and successful.", summary: "Simon Sinek discovered that great leaders all start with WHY. This simple but powerful idea has transformed how millions think about their work and lives.", themes: ["Purpose", "Leadership", "Inspiration", "Meaning"], music: "Explosions in the Sky", music_genre: "fantasy", cover_color: "#FCD34D", year: 2009, pages: 256, reading_time: "6-7 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 35, title: "The Second Mountain", author: "David Brooks", genre: "non-fiction", mood: ["purpose", "meaning", "community", "commitment", "healing"], description: "What happens after you have achieved everything and it still is not enough.", summary: "David Brooks writes about people who found achievement hollow and climbed a second mountain of commitment. Joy comes not from self-fulfilment but from self-surrender.", themes: ["Purpose", "Meaning", "Commitment", "Community", "Joy"], music: "Bach - Cello Suite No. 1", music_genre: "historical", cover_color: "#D97706", year: 2019, pages: 320, reading_time: "8-9 hours", rating: 4.4, difficulty: "moderate", language: "English" },
  { id: 36, title: "The Body Keeps the Score", author: "Bessel van der Kolk", genre: "non-fiction", mood: ["trauma", "healing", "mental health", "recovery", "understanding"], description: "How trauma reshapes mind and body and what can heal it.", summary: "Bessel van der Kolk draws on 30 years of research to show how trauma literally reshapes the brain and body and explains revolutionary treatments now available.", themes: ["Trauma", "Healing", "Neuroscience", "Recovery", "Body"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "literary", cover_color: "#93C5FD", year: 2014, pages: 464, reading_time: "12-14 hours", rating: 4.8, difficulty: "challenging", language: "English" },
  { id: 37, title: "Waking the Tiger", author: "Peter Levine", genre: "non-fiction", mood: ["trauma", "healing", "body", "recovery", "peace"], description: "Healing trauma through the body's natural ability to recover.", summary: "Peter Levine explains how somatic techniques can release stuck trauma. Wild animals rarely develop trauma and we can learn from them.", themes: ["Trauma", "Body", "Healing", "Recovery", "Nature"], music: "Brian Eno - Music for Airports", music_genre: "default", cover_color: "#6EE7B7", year: 1997, pages: 288, reading_time: "7-8 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 38, title: "Feel the Fear and Do It Anyway", author: "Susan Jeffers", genre: "self-help", mood: ["fear", "courage", "change", "confidence", "growth"], description: "How to turn fear and indecision into confidence and action.", summary: "Everyone feels fear when they step outside their comfort zone. The goal is not to eliminate fear but to act despite it.", themes: ["Fear", "Courage", "Change", "Confidence", "Action"], music: "Explosions in the Sky", music_genre: "selfhelp", cover_color: "#FCD34D", year: 1987, pages: 224, reading_time: "5-6 hours", rating: 4.4, difficulty: "easy", language: "English" },
  { id: 39, title: "Daring Greatly", author: "Brene Brown", genre: "self-help", mood: ["vulnerability", "courage", "shame", "connection", "wholehearted living"], description: "How the courage to be vulnerable transforms the way we live and love.", summary: "Brene Brown argues that vulnerability is the birthplace of love, belonging, joy, and creativity. Far from weakness it is our most accurate measure of courage.", themes: ["Vulnerability", "Courage", "Shame", "Connection", "Authenticity"], music: "Bon Iver - Holocene", music_genre: "selfhelp", cover_color: "#F472B6", year: 2012, pages: 320, reading_time: "7-8 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 40, title: "Walden", author: "Henry David Thoreau", genre: "non-fiction", mood: ["solitude", "nature", "simplicity", "purpose", "peace"], description: "Two years living deliberately in the woods.", summary: "In 1845 Thoreau moved to a small cabin on the shores of Walden Pond and lived simply for two years. A meditation on solitude and the beauty of nature.", themes: ["Solitude", "Nature", "Simplicity", "Deliberate Living"], music: "Bach - Cello Suite No. 1", music_genre: "historical", cover_color: "#6EE7B7", year: 1854, pages: 312, reading_time: "8-10 hours", rating: 4.4, difficulty: "challenging", language: "English" },
  { id: 41, title: "A Field Guide to Getting Lost", author: "Rebecca Solnit", genre: "non-fiction", mood: ["solitude", "wonder", "loss", "identity", "peace"], description: "A meditation on wandering getting lost and finding yourself.", summary: "Rebecca Solnit meditates on what it means to be lost. To be lost is to be fully present freed from the tyranny of knowing exactly where you are.", themes: ["Wandering", "Solitude", "Memory", "Wonder", "Identity"], music: "Debussy - Clair de Lune", music_genre: "literary", cover_color: "#93C5FD", year: 2005, pages: 224, reading_time: "5-6 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 42, title: "Self-Compassion", author: "Kristin Neff", genre: "self-help", mood: ["self-worth", "shame", "healing", "kindness", "inner critic"], description: "Why you need to treat yourself the way you would treat a good friend.", summary: "Kristin Neff is the world's leading researcher on self-compassion. Treating yourself with kindness is the foundation of emotional resilience.", themes: ["Self-compassion", "Kindness", "Inner Critic", "Healing", "Resilience"], music: "Nils Frahm - Says", music_genre: "default", cover_color: "#FCA5A5", year: 2011, pages: 320, reading_time: "8-9 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 43, title: "You Are a Badass", author: "Jen Sincero", genre: "self-help", mood: ["self-worth", "motivation", "confidence", "change", "humor"], description: "How to stop doubting your greatness and start living an awesome life.", summary: "Jen Sincero writes with irreverent humor about how to change the self-sabotaging beliefs that keep us small.", themes: ["Confidence", "Self-worth", "Motivation", "Change", "Humor"], music: "Lizzo - Good as Hell", music_genre: "selfhelp", cover_color: "#FCD34D", year: 2013, pages: 256, reading_time: "5-6 hours", rating: 4.4, difficulty: "easy", language: "English" },
  { id: 44, title: "A Man Called Ove", author: "Fredrik Backman", genre: "fiction", mood: ["grief", "loneliness", "community", "healing", "joy"], description: "A grumpy man who has given up on life is saved by his annoying neighbours.", summary: "Ove is 59 alone since his wife died and determined to end his life. Then a young family keeps accidentally interrupting his plans. Funny heartbreaking and deeply affirming.", themes: ["Grief", "Community", "Loneliness", "Friendship", "Purpose"], music: "Yann Tiersen", music_genre: "romance", cover_color: "#6B7280", year: 2012, pages: 337, reading_time: "8-9 hours", rating: 4.8, difficulty: "easy", language: "Swedish/English" },
  { id: 45, title: "The Midnight Library", author: "Matt Haig", genre: "fiction", mood: ["depression", "regret", "hope", "purpose", "healing"], description: "Between life and death lies a library where every book is another life you could have lived.", summary: "Nora Seed finds herself in a magical library between life and death. As she explores parallel lives she discovers that the life she has been living might be worth returning to.", themes: ["Regret", "Depression", "Hope", "Choice", "Living"], music: "Coldplay - Yellow", music_genre: "fantasy", cover_color: "#6EE7B7", year: 2020, pages: 304, reading_time: "6-7 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 46, title: "Flowers for Algernon", author: "Daniel Keyes", genre: "fiction", mood: ["identity", "loneliness", "grief", "wonder", "human connection"], description: "A man's IQ is tripled by surgery but at what cost.", summary: "Charlie Gordon undergoes experimental brain surgery that triples his intelligence. Told in journal entries one of the most emotionally devastating explorations of identity and loneliness ever written.", themes: ["Identity", "Intelligence", "Loneliness", "Human Connection", "Loss"], music: "Max Richter - On the Nature of Daylight", music_genre: "literary", cover_color: "#A78BFA", year: 1966, pages: 311, reading_time: "7-8 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 47, title: "The Diary of a Young Girl", author: "Anne Frank", genre: "memoir", mood: ["hope", "resilience", "fear", "courage", "identity"], description: "Anne Frank's diary written while hiding from the Nazis.", summary: "Anne Frank was 13 when her family went into hiding in Amsterdam. For two years she kept a diary. One of the most important documents of the 20th century.", themes: ["Hope", "Resilience", "Fear", "Adolescence", "History"], music: "Samuel Barber - Adagio for Strings", music_genre: "historical", cover_color: "#D97706", year: 1947, pages: 283, reading_time: "7-8 hours", rating: 4.8, difficulty: "easy", language: "Dutch/English" },
  { id: 48, title: "I Know Why the Caged Bird Sings", author: "Maya Angelou", genre: "memoir", mood: ["trauma", "resilience", "identity", "courage", "healing"], description: "Maya Angelou's memoir of childhood and identity in a racist American South.", summary: "Maya Angelou describes her early years growing up Black in the Jim Crow South. Written with extraordinary power and beauty.", themes: ["Racism", "Identity", "Resilience", "Trauma", "Courage"], music: "Nina Simone - Feeling Good", music_genre: "memoir", cover_color: "#1F2937", year: 1969, pages: 289, reading_time: "7-8 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 49, title: "Full Catastrophe Living", author: "Jon Kabat-Zinn", genre: "self-help", mood: ["stress", "anxiety", "healing", "mindfulness", "chronic pain"], description: "Using the wisdom of your body and mind to face stress pain and illness.", summary: "Jon Kabat-Zinn founded Mindfulness-Based Stress Reduction and this book is its definitive guide. Shows how mindfulness meditation can help with stress anxiety and chronic pain.", themes: ["Mindfulness", "Stress", "Healing", "Meditation", "Chronic Illness"], music: "Brian Eno - Music for Airports", music_genre: "default", cover_color: "#6EE7B7", year: 1990, pages: 720, reading_time: "18-20 hours", rating: 4.7, difficulty: "challenging", language: "English" },
  { id: 50, title: "When the Body Says No", author: "Gabor Mate", genre: "non-fiction", mood: ["healing", "stress", "trauma", "mental health", "body"], description: "The hidden costs of hidden stress and how emotions affect physical health.", summary: "Gabor Mate shows how repressed emotions chronic stress and unresolved trauma manifest as illness in the body. Both scientifically rigorous and deeply compassionate.", themes: ["Mind-Body Connection", "Stress", "Trauma", "Healing", "Repression"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "default", cover_color: "#78716C", year: 2003, pages: 320, reading_time: "8-9 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 51, title: "It's OK That You're Not OK", author: "Megan Devine", genre: "self-help", mood: ["grief", "loss", "healing", "validation"], description: "A compassionate guide that validates grief rather than trying to fix it.", summary: "Megan Devine argues that grief does not need to be fixed it needs to be witnessed. Offers radical validation for the grieving.", themes: ["Grief", "Validation", "Healing", "Loss"], music: "Max Richter - On the Nature of Daylight", music_genre: "literary", cover_color: "#9CA3AF", year: 2017, pages: 240, reading_time: "5-6 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 52, title: "The Light We Carry", author: "Michelle Obama", genre: "memoir", mood: ["hope", "resilience", "identity", "courage", "healing"], description: "Michelle Obama shares tools and practices that help her navigate an uncertain world.", summary: "Michelle Obama reflects on the tools and practices that keep her grounded. A warm practical book about building resilience.", themes: ["Resilience", "Hope", "Identity", "Courage", "Growth"], music: "Nina Simone - Feeling Good", music_genre: "selfhelp", cover_color: "#F472B6", year: 2022, pages: 320, reading_time: "7-8 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 53, title: "Anxious People", author: "Fredrik Backman", genre: "fiction", mood: ["anxiety", "humor", "connection", "hope", "healing"], description: "A hostage situation goes wrong and becomes unexpectedly touching.", summary: "A failed bank robber accidentally takes a group of strangers hostage. Funny tender and deeply human about the fact that people are mostly trying their best.", themes: ["Anxiety", "Connection", "Humor", "Forgiveness", "Hope"], music: "Yann Tiersen", music_genre: "romance", cover_color: "#FDE68A", year: 2019, pages: 352, reading_time: "8-9 hours", rating: 4.6, difficulty: "easy", language: "Swedish/English" },
  { id: 54, title: "Rising Strong", author: "Brene Brown", genre: "self-help", mood: ["resilience", "failure", "courage", "healing", "hope"], description: "How to rise after falling — the physics of vulnerability.", summary: "Brene Brown argues that the most transformative experiences often come after we have fallen. Rising Strong is about what it takes to get back up.", themes: ["Resilience", "Failure", "Courage", "Vulnerability", "Growth"], music: "Bon Iver - Holocene", music_genre: "selfhelp", cover_color: "#FCA5A5", year: 2015, pages: 336, reading_time: "7-8 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 55, title: "Together", author: "Vivek Murthy", genre: "non-fiction", mood: ["loneliness", "connection", "community", "healing", "belonging"], description: "The healing power of human connection in a sometimes lonely world.", summary: "The US Surgeon General explores the loneliness epidemic and makes a compelling case for why human connection is as essential to health as diet and exercise.", themes: ["Loneliness", "Connection", "Community", "Health", "Belonging"], music: "Norah Jones - Come Away With Me", music_genre: "romance", cover_color: "#6EE7B7", year: 2020, pages: 320, reading_time: "7-8 hours", rating: 4.5, difficulty: "moderate", language: "English" },
  { id: 56, title: "Becoming", author: "Michelle Obama", genre: "memoir", mood: ["identity", "purpose", "resilience", "hope", "self-discovery"], description: "Michelle Obama's journey from the South Side of Chicago to the White House.", summary: "Michelle Obama chronicles her journey with candor and grace. About becoming never quite arriving always evolving.", themes: ["Identity", "Purpose", "Resilience", "Race", "Growth"], music: "Nina Simone - Feeling Good", music_genre: "memoir", cover_color: "#1F2937", year: 2018, pages: 426, reading_time: "10-12 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 57, title: "Siddhartha", author: "Hermann Hesse", genre: "fiction", mood: ["spirituality", "wisdom", "journey", "peace", "meaning"], description: "A spiritual journey of self-discovery in ancient India.", summary: "A young man leaves his privileged life to seek enlightenment. Hesse's luminous novel follows Siddhartha through asceticism love wealth and ultimately the banks of a river where wisdom finally arrives.", themes: ["Spirituality", "Journey", "Wisdom", "Enlightenment", "Peace"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "historical", cover_color: "#D97706", year: 1922, pages: 152, reading_time: "3-4 hours", rating: 4.7, difficulty: "moderate", language: "German/English" },
  { id: 58, title: "All About Love", author: "bell hooks", genre: "non-fiction", mood: ["love", "relationships", "healing", "wisdom", "connection"], description: "A visionary thinker examines the concept of love.", summary: "bell hooks argues that love is not just a feeling but a practice combining care commitment knowledge responsibility respect and trust.", themes: ["Love", "Relationships", "Growth", "Wisdom", "Connection"], music: "Norah Jones - Come Away With Me", music_genre: "romance", cover_color: "#F472B6", year: 2000, pages: 240, reading_time: "5-6 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 59, title: "Normal People", author: "Sally Rooney", genre: "fiction", mood: ["love", "connection", "identity", "loneliness", "relationships"], description: "Two young people navigate love class and connection in contemporary Ireland.", summary: "Connell and Marianne grow up in the same small town but move in different worlds. A love story that explores power communication and what it means to truly know another person.", themes: ["Love", "Class", "Identity", "Connection", "Communication"], music: "Bon Iver - Skinny Love", music_genre: "romance", cover_color: "#FCA5A5", year: 2018, pages: 273, reading_time: "6-7 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 60, title: "Eat Pray Love", author: "Elizabeth Gilbert", genre: "memoir", mood: ["love", "self-discovery", "healing", "journey", "spirituality"], description: "One woman's search for everything across Italy India and Indonesia.", summary: "After a painful divorce Elizabeth Gilbert embarks on a year of travel eating in Italy praying in India loving in Bali. About pleasure devotion and balance.", themes: ["Self-discovery", "Love", "Healing", "Journey", "Spirituality"], music: "Norah Jones - Come Away With Me", music_genre: "romance", cover_color: "#FDE68A", year: 2006, pages: 352, reading_time: "8-9 hours", rating: 4.4, difficulty: "easy", language: "English" },
  { id: 61, title: "Ikigai", author: "Hector Garcia and Francesc Miralles", genre: "non-fiction", mood: ["purpose", "meaning", "joy", "longevity", "balance"], description: "The Japanese secret to a long and happy life.", summary: "The authors traveled to Okinawa Japan home of the world's longest-lived people to uncover the secret of ikigai: the reason to get up in the morning.", themes: ["Purpose", "Meaning", "Joy", "Longevity", "Balance"], music: "Brian Eno - 1/1", music_genre: "default", cover_color: "#FCD34D", year: 2016, pages: 208, reading_time: "4-5 hours", rating: 4.5, difficulty: "easy", language: "Spanish/English" },
  { id: 62, title: "Atomic Habits", author: "James Clear", genre: "self-help", mood: ["change", "motivation", "growth", "discipline", "purpose"], description: "Tiny changes remarkable results.", summary: "James Clear argues that habits are the compound interest of self-improvement. Small incremental changes just 1 percent better each day lead to remarkable results over time.", themes: ["Habits", "Change", "Growth", "Discipline", "Identity"], music: "Uplifting Morning", music_genre: "selfhelp", cover_color: "#34D399", year: 2018, pages: 320, reading_time: "7-8 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 63, title: "The War of Art", author: "Steven Pressfield", genre: "non-fiction", mood: ["courage", "creativity", "fear", "purpose", "motivation"], description: "Break through the blocks and win your inner creative battles.", summary: "Steven Pressfield identifies Resistance the force that prevents us from doing our creative work and shows how to overcome it. Essential for any artist writer or entrepreneur.", themes: ["Creativity", "Resistance", "Courage", "Discipline", "Art"], music: "Explosions in the Sky", music_genre: "selfhelp", cover_color: "#374151", year: 2002, pages: 168, reading_time: "3-4 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 64, title: "Wild", author: "Cheryl Strayed", genre: "memoir", mood: ["healing", "nature", "grief", "resilience", "self-discovery"], description: "A solo hike along the Pacific Crest Trail to heal a shattered life.", summary: "After her mother's death and her marriage's collapse Cheryl Strayed hikes 1100 miles alone. Raw and redemptive one of the best memoirs of the decade.", themes: ["Nature", "Healing", "Grief", "Resilience", "Self-discovery"], music: "Bon Iver - Holocene", music_genre: "memoir", cover_color: "#D97706", year: 2012, pages: 315, reading_time: "7-8 hours", rating: 4.7, difficulty: "easy", language: "English" },
  { id: 65, title: "Maybe You Should Talk to Someone", author: "Lori Gottlieb", genre: "memoir", mood: ["healing", "therapy", "self-discovery", "humor", "mental health"], description: "A therapist goes to therapy and discovers more than she expected.", summary: "Lori Gottlieb is a therapist who finds herself in crisis and goes to therapy herself. With humor and honesty she shows how therapy works and why we all need it.", themes: ["Therapy", "Healing", "Self-discovery", "Humor", "Change"], music: "Nils Frahm - Says", music_genre: "literary", cover_color: "#A78BFA", year: 2019, pages: 432, reading_time: "10-12 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 66, title: "Radical Acceptance", author: "Tara Brach", genre: "spiritual", mood: ["trauma", "shame", "healing", "self-compassion", "peace"], description: "Embracing your life with the heart of a Buddha.", summary: "Tara Brach shows how the trance of unworthiness is the source of much suffering. Through mindfulness and compassion we can learn radical acceptance.", themes: ["Acceptance", "Shame", "Healing", "Mindfulness", "Self-compassion"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "default", cover_color: "#6EE7B7", year: 2003, pages: 352, reading_time: "8-9 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 67, title: "Meditations", author: "Marcus Aurelius", genre: "spiritual", mood: ["wisdom", "peace", "stoicism", "purpose", "resilience"], description: "The private journal of a Roman emperor one of the greatest philosophical works.", summary: "Written as private notes to himself Marcus Aurelius recorded his thoughts on how to live virtuously amid the pressures of power. The foundation of Stoic philosophy.", themes: ["Wisdom", "Stoicism", "Peace", "Virtue", "Resilience"], music: "Bach - Cello Suite No. 1", music_genre: "historical", cover_color: "#78716C", year: 180, pages: 254, reading_time: "6-7 hours", rating: 4.8, difficulty: "moderate", language: "Greek/English" },
  { id: 68, title: "The Obstacle Is the Way", author: "Ryan Holiday", genre: "non-fiction", mood: ["resilience", "stoicism", "courage", "purpose", "wisdom"], description: "The timeless art of turning trials into triumph.", summary: "Ryan Holiday draws on Stoic philosophy to show how our greatest obstacles can become our greatest opportunities.", themes: ["Stoicism", "Resilience", "Courage", "Wisdom", "Growth"], music: "Bach - Cello Suite No. 1", music_genre: "historical", cover_color: "#6B7280", year: 2014, pages: 224, reading_time: "5-6 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 69, title: "Letters to a Young Poet", author: "Rainer Maria Rilke", genre: "poetry", mood: ["wisdom", "creativity", "solitude", "patience", "beauty"], description: "Rilke's letters of advice to a young aspiring poet wisdom for all of us.", summary: "Ten letters Rilke wrote to a young soldier who aspired to be a poet. About patience solitude the necessity of difficulty and the deep questions of life.", themes: ["Wisdom", "Creativity", "Solitude", "Patience", "Art"], music: "Satie - Gymnopedie", music_genre: "poetry", cover_color: "#78716C", year: 1929, pages: 96, reading_time: "2-3 hours", rating: 4.7, difficulty: "moderate", language: "German/English" },
  { id: 70, title: "The God of Small Things", author: "Arundhati Roy", genre: "fiction", mood: ["love", "grief", "identity", "injustice", "beauty"], description: "A sweeping story of forbidden love and family tragedy in Kerala.", summary: "In Kerala India the lives of twin siblings are shaped by a tragedy rooted in forbidden love and the rigid caste system. One of the most beautiful and devastating novels ever written.", themes: ["Love", "Grief", "Injustice", "Family", "Beauty"], music: "Ravi Shankar", music_genre: "romance", cover_color: "#D97706", year: 1997, pages: 321, reading_time: "8-9 hours", rating: 4.7, difficulty: "challenging", language: "English" },
  { id: 71, title: "The White Tiger", author: "Aravind Adiga", genre: "fiction", mood: ["identity", "injustice", "courage", "purpose", "social change"], description: "A darkly comic novel about class and corruption in modern India.", summary: "Balram Halwai rises from rural poverty to become a successful entrepreneur through murder. A scathing darkly funny portrait of modern India and class struggle. Booker Prize winner.", themes: ["Class", "Identity", "Injustice", "Ambition", "India"], music: "Tabla and Sitar", music_genre: "historical", cover_color: "#1F2937", year: 2008, pages: 321, reading_time: "7-8 hours", rating: 4.5, difficulty: "moderate", language: "English" },
  { id: 72, title: "The Namesake", author: "Jhumpa Lahiri", genre: "fiction", mood: ["identity", "belonging", "family", "grief", "loneliness"], description: "An immigrant family navigates between Indian and American worlds.", summary: "The Ganguli family moves from Calcutta to Boston. Their son Gogol navigates between the Indian world of his parents and the American world he grows up in.", themes: ["Identity", "Belonging", "Family", "Immigration", "Grief"], music: "Ravi Shankar", music_genre: "memoir", cover_color: "#FCA5A5", year: 2003, pages: 291, reading_time: "7-8 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 73, title: "Interpreter of Maladies", author: "Jhumpa Lahiri", genre: "fiction", mood: ["loneliness", "love", "identity", "connection", "belonging"], description: "Stories of Indians and Indian-Americans searching for connection.", summary: "Nine exquisitely crafted stories about the lives of Indians and Indian-Americans. Pulitzer Prize winner. Each story illuminates the distances between cultures and between people who love each other.", themes: ["Loneliness", "Love", "Identity", "Connection", "Belonging"], music: "Ravi Shankar", music_genre: "literary", cover_color: "#D97706", year: 1999, pages: 198, reading_time: "5-6 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 74, title: "Pride and Prejudice", author: "Jane Austen", genre: "fiction", mood: ["love", "humor", "identity", "society", "joy"], description: "The most beloved romance in English literature.", summary: "Elizabeth Bennet and Mr. Darcy navigate love class and misunderstanding in Regency England. Austen's wit makes this as fresh and funny as the day it was written.", themes: ["Love", "Humor", "Identity", "Society", "Marriage"], music: "Mozart - Piano Sonata No. 16", music_genre: "romance", cover_color: "#F472B6", year: 1813, pages: 432, reading_time: "10-12 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 75, title: "Jane Eyre", author: "Charlotte Bronte", genre: "fiction", mood: ["love", "identity", "resilience", "courage", "healing"], description: "A passionate tale of love independence and moral courage.", summary: "Orphaned Jane Eyre becomes a governess and falls in love with her brooding employer Mr. Rochester. A fiercely independent heroine a passionate love story and a meditation on moral integrity.", themes: ["Love", "Identity", "Independence", "Courage", "Resilience"], music: "Chopin - Nocturne in E-flat major", music_genre: "romance", cover_color: "#78716C", year: 1847, pages: 507, reading_time: "13-15 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 76, title: "The Kite Runner", author: "Khaled Hosseini", genre: "fiction", mood: ["guilt", "redemption", "love", "friendship", "healing"], description: "A powerful story of betrayal and redemption set in Afghanistan.", summary: "After a devastating act of cowardice Amir spends decades seeking redemption. A sweeping story of fathers and sons friendship betrayal and the possibility of forgiveness.", themes: ["Redemption", "Guilt", "Friendship", "Love", "Afghanistan"], music: "Arvo Part - Spiegel im Spiegel", music_genre: "literary", cover_color: "#D97706", year: 2003, pages: 372, reading_time: "9-10 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 77, title: "Factfulness", author: "Hans Rosling", genre: "non-fiction", mood: ["hope", "wonder", "positivity", "curiosity", "optimism"], description: "Ten reasons we're wrong about the world and why things are better than you think.", summary: "Hans Rosling shows with data that the world is in much better shape than we think. A remedy for negativity bias and a genuinely hopeful book about human progress.", themes: ["Hope", "Data", "Optimism", "Curiosity", "Progress"], music: "Uplifting Morning", music_genre: "selfhelp", cover_color: "#34D399", year: 2018, pages: 352, reading_time: "8-9 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 78, title: "Long Walk to Freedom", author: "Nelson Mandela", genre: "memoir", mood: ["hope", "resilience", "justice", "purpose", "courage"], description: "Nelson Mandela's extraordinary autobiography.", summary: "Nelson Mandela's account of his life from rural childhood to 27 years in prison to becoming President of South Africa. A story of extraordinary courage and moral clarity.", themes: ["Hope", "Justice", "Resilience", "Courage", "Leadership"], music: "Nina Simone - Feeling Good", music_genre: "selfhelp", cover_color: "#1F2937", year: 1994, pages: 656, reading_time: "16-18 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 79, title: "To Kill a Mockingbird", author: "Harper Lee", genre: "fiction", mood: ["justice", "courage", "identity", "loss", "wisdom"], description: "A story of racial injustice and the loss of innocence in the American South.", summary: "Scout Finch grows up in Alabama as her father Atticus Finch defends a Black man accused of a crime he did not commit. About justice courage and seeing the world through another's eyes.", themes: ["Justice", "Courage", "Racism", "Childhood", "Wisdom"], music: "Bach - Cello Suite No. 1", music_genre: "historical", cover_color: "#D97706", year: 1960, pages: 281, reading_time: "7-8 hours", rating: 4.8, difficulty: "easy", language: "English" },
  { id: 80, title: "The Remains of the Day", author: "Kazuo Ishiguro", genre: "fiction", mood: ["regret", "identity", "dignity", "loneliness", "memory"], description: "A butler reflects on a life of service and the regrets left in its wake.", summary: "Stevens an English butler reflects on his years of service and the emotional repression that kept him from love and authentic connection. Quiet devastating and deeply moving. Booker Prize winner.", themes: ["Regret", "Dignity", "Loneliness", "Memory", "Identity"], music: "Debussy - Clair de Lune", music_genre: "literary", cover_color: "#78716C", year: 1989, pages: 258, reading_time: "6-7 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 81, title: "Into the Wild", author: "Jon Krakauer", genre: "non-fiction", mood: ["adventure", "freedom", "identity", "nature", "purpose"], description: "The true story of Christopher McCandless who walked into the Alaskan wilderness.", summary: "In 1992 Christopher McCandless hitchhiked to Alaska and walked into the wilderness alone. A meditation on idealism the call of the wild and the fine line between courage and recklessness.", themes: ["Adventure", "Freedom", "Nature", "Identity", "Youth"], music: "Eddie Vedder - Society", music_genre: "memoir", cover_color: "#D97706", year: 1996, pages: 224, reading_time: "5-6 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 82, title: "Shantaram", author: "Gregory David Roberts", genre: "fiction", mood: ["adventure", "redemption", "identity", "love", "freedom"], description: "A fugitive finds a new life in the slums of Bombay.", summary: "An Australian fugitive escapes to Bombay and finds himself living in a slum running a makeshift medical clinic and falling in love. A sweeping epic novel about redemption and India.", themes: ["Adventure", "Redemption", "Love", "Identity", "India"], music: "Ravi Shankar", music_genre: "historical", cover_color: "#D97706", year: 2003, pages: 944, reading_time: "25-30 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 83, title: "Sophie's World", author: "Jostein Gaarder", genre: "fiction", mood: ["wonder", "wisdom", "curiosity", "identity", "philosophy"], description: "A history of philosophy told through a magical story.", summary: "14-year-old Sophie receives mysterious letters from a philosopher and embarks on a crash course in the history of Western philosophy. A remarkable novel that makes complex ideas accessible and thrilling.", themes: ["Philosophy", "Wonder", "Curiosity", "Identity", "Wisdom"], music: "Debussy - Clair de Lune", music_genre: "literary", cover_color: "#A78BFA", year: 1991, pages: 518, reading_time: "13-15 hours", rating: 4.6, difficulty: "moderate", language: "Norwegian/English" },
  { id: 84, title: "The Happiness Advantage", author: "Shawn Achor", genre: "non-fiction", mood: ["joy", "happiness", "positivity", "success", "motivation"], description: "How a positive brain fuels success in work and life.", summary: "Shawn Achor a Harvard researcher argues that happiness fuels success not the other way around. Shares seven principles for improving performance and experiencing more joy.", themes: ["Happiness", "Positivity", "Success", "Motivation", "Joy"], music: "Uplifting Morning", music_genre: "selfhelp", cover_color: "#FCD34D", year: 2010, pages: 256, reading_time: "5-6 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 85, title: "The Art of Happiness", author: "Dalai Lama and Howard Cutler", genre: "non-fiction", mood: ["happiness", "peace", "wisdom", "spirituality", "joy"], description: "A psychiatrist and the Dalai Lama explore the very nature of happiness.", summary: "The Dalai Lama's central message: the purpose of our existence is to seek happiness and it is achievable through training the mind.", themes: ["Happiness", "Peace", "Wisdom", "Spirituality", "Compassion"], music: "Tibetan Singing Bowls", music_genre: "poetry", cover_color: "#FCD34D", year: 1998, pages: 322, reading_time: "7-8 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 86, title: "The Monk Who Sold His Ferrari", author: "Robin Sharma", genre: "fiction", mood: ["purpose", "wisdom", "simplicity", "peace", "meaning"], description: "A fable about fulfilling your dreams and reaching your destiny.", summary: "A high-powered lawyer suffers a heart attack and embarks on a journey of transformation. He returns with ancient wisdom about living with purpose cultivating joy and embracing the present moment.", themes: ["Purpose", "Wisdom", "Simplicity", "Transformation", "Peace"], music: "Sitar and Tabla", music_genre: "historical", cover_color: "#FCD34D", year: 1997, pages: 198, reading_time: "4-5 hours", rating: 4.3, difficulty: "easy", language: "English" },
  { id: 87, title: "The Curious Incident of the Dog in the Night-Time", author: "Mark Haddon", genre: "fiction", mood: ["wonder", "identity", "courage", "difference", "journey"], description: "A mystery told by a 15-year-old with autism unlike anything you have read.", summary: "Christopher Boone investigates the murder of his neighbor's dog. Told from his unique perspective this novel is funny sad and profoundly illuminating about difference and courage.", themes: ["Identity", "Difference", "Courage", "Family", "Wonder"], music: "Nils Frahm - Says", music_genre: "scifi", cover_color: "#34D399", year: 2003, pages: 226, reading_time: "5-6 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 88, title: "The Snow Leopard", author: "Peter Matthiessen", genre: "memoir", mood: ["solitude", "nature", "spirituality", "grief", "wonder"], description: "A journey to the Himalayas in search of the snow leopard and himself.", summary: "Peter Matthiessen treks into the Himalayas after his wife's death from cancer. Part travel memoir part spiritual quest one of the greatest nature writing books ever written.", themes: ["Nature", "Solitude", "Grief", "Spirituality", "Wonder"], music: "Brian Eno - 1/1", music_genre: "default", cover_color: "#93C5FD", year: 1978, pages: 338, reading_time: "8-9 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 89, title: "The Six Pillars of Self-Esteem", author: "Nathaniel Branden", genre: "self-help", mood: ["self-worth", "confidence", "identity", "healing", "growth"], description: "The definitive work on self-esteem by the father of the self-esteem movement.", summary: "Nathaniel Branden identifies six practices essential to building genuine self-esteem including living consciously self-acceptance self-responsibility and personal integrity.", themes: ["Self-esteem", "Confidence", "Identity", "Growth", "Integrity"], music: "Classical Piano", music_genre: "literary", cover_color: "#A78BFA", year: 1994, pages: 336, reading_time: "8-9 hours", rating: 4.5, difficulty: "moderate", language: "English" },
  { id: 90, title: "Joyful", author: "Ingrid Fetell Lee", genre: "non-fiction", mood: ["joy", "wonder", "happiness", "creativity", "beauty"], description: "The surprising power of ordinary things to create extraordinary happiness.", summary: "Designer Ingrid Fetell Lee explores how physical spaces and objects shape our inner experience. The hidden aesthetics of joy. Surprising beautiful and immediately practical.", themes: ["Joy", "Design", "Beauty", "Wonder", "Happiness"], music: "Yann Tiersen", music_genre: "romance", cover_color: "#FCD34D", year: 2018, pages: 320, reading_time: "7-8 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 91, title: "The Motorcycle Diaries", author: "Ernesto Che Guevara", genre: "memoir", mood: ["adventure", "discovery", "justice", "identity", "journey"], description: "A young Che Guevara travels South America and discovers the world.", summary: "Before he became a revolutionary a 23-year-old Guevara and his friend traveled 8000 miles across South America on a motorcycle. A coming-of-age story about encountering poverty and injustice.", themes: ["Adventure", "Discovery", "Justice", "Identity", "Journey"], music: "Rodrigo y Gabriela", music_genre: "memoir", cover_color: "#6B7280", year: 1952, pages: 175, reading_time: "4-5 hours", rating: 4.4, difficulty: "easy", language: "Spanish/English" },
  { id: 92, title: "The War of Art", author: "Steven Pressfield", genre: "non-fiction", mood: ["creativity", "fear", "courage", "discipline", "purpose"], description: "Identify and overcome Resistance the enemy of creative work.", summary: "Steven Pressfield names the invisible force that stops us from doing our work and shows us how to defeat it. Essential for writers artists entrepreneurs and anyone with a dream.", themes: ["Creativity", "Resistance", "Discipline", "Courage", "Work"], music: "Explosions in the Sky", music_genre: "selfhelp", cover_color: "#374151", year: 2002, pages: 165, reading_time: "3-4 hours", rating: 4.6, difficulty: "easy", language: "English" },
  { id: 93, title: "Thinking Fast and Slow", author: "Daniel Kahneman", genre: "non-fiction", mood: ["curiosity", "wisdom", "understanding", "self-discovery", "wonder"], description: "How two systems in our brain shape the way we think and make decisions.", summary: "Nobel laureate Daniel Kahneman explains the two systems that drive the way we think. System 1 is fast intuitive and emotional. System 2 is slow deliberate and logical. A masterwork of psychology.", themes: ["Psychology", "Decision Making", "Curiosity", "Wisdom", "Understanding"], music: "Bach - Cello Suite No. 1", music_genre: "literary", cover_color: "#6B7280", year: 2011, pages: 499, reading_time: "13-15 hours", rating: 4.6, difficulty: "challenging", language: "English" },
  { id: 94, title: "The Alchemist Code", author: "Elif Shafak", genre: "fiction", mood: ["love", "spirituality", "wisdom", "history", "beauty"], description: "A mystical love story set across centuries and cultures.", summary: "Elif Shafak weaves together stories across time and place exploring love spirituality and the connection between East and West through Sufi philosophy and stunning prose.", themes: ["Love", "Spirituality", "History", "Wisdom", "Beauty"], music: "Oud and Strings", music_genre: "historical", cover_color: "#C084FC", year: 2010, pages: 352, reading_time: "8-9 hours", rating: 4.5, difficulty: "moderate", language: "Turkish/English" },
  { id: 95, title: "Hamnet", author: "Maggie O'Farrell", genre: "fiction", mood: ["grief", "love", "loss", "family", "healing"], description: "A devastating and beautiful novel about the death of Shakespeare's son.", summary: "In 1596 Agnes and her husband's young son Hamnet falls gravely ill. Maggie O'Farrell imagines the story behind Shakespeare's most famous play. A profound and beautiful meditation on grief and love.", themes: ["Grief", "Love", "Loss", "Family", "Healing"], music: "Max Richter - On the Nature of Daylight", music_genre: "literary", cover_color: "#78716C", year: 2020, pages: 301, reading_time: "7-8 hours", rating: 4.7, difficulty: "moderate", language: "English" },
  { id: 96, title: "When We Cease to Understand the World", author: "Benjamin Labatut", genre: "fiction", mood: ["wonder", "curiosity", "fear", "knowledge", "identity"], description: "How the greatest minds of the 20th century lost themselves in their discoveries.", summary: "Benjamin Labatut tells the stories of scientists and mathematicians whose discoveries changed everything. A haunting meditation on the dark side of genius and the terror of knowledge.", themes: ["Wonder", "Knowledge", "Fear", "Discovery", "Identity"], music: "Brian Eno - Music for Airports", music_genre: "scifi", cover_color: "#1F2937", year: 2020, pages: 224, reading_time: "5-6 hours", rating: 4.6, difficulty: "challenging", language: "Spanish/English" },
  { id: 97, title: "A Gentleman in Moscow", author: "Amor Towles", genre: "fiction", mood: ["joy", "resilience", "wisdom", "beauty", "hope"], description: "A count is placed under house arrest in a Moscow hotel for decades.", summary: "Count Alexander Rostov is sentenced to spend the rest of his life inside Moscow's Metropol Hotel. What follows is a masterful novel about finding beauty and meaning within constraints.", themes: ["Joy", "Resilience", "Beauty", "Wisdom", "Hope"], music: "Mozart - Piano Concerto No. 21", music_genre: "historical", cover_color: "#D97706", year: 2016, pages: 462, reading_time: "11-13 hours", rating: 4.8, difficulty: "moderate", language: "English" },
  { id: 98, title: "The Joy Luck Club", author: "Amy Tan", genre: "fiction", mood: ["love", "identity", "family", "belonging", "grief"], description: "Four Chinese immigrant mothers and their American-born daughters.", summary: "Four Chinese immigrant mothers and their American-born daughters navigate the complex terrain between cultures generations and the stories we tell about ourselves and each other.", themes: ["Love", "Identity", "Family", "Immigration", "Grief"], music: "Traditional Chinese Music", music_genre: "historical", cover_color: "#F472B6", year: 1989, pages: 288, reading_time: "7-8 hours", rating: 4.6, difficulty: "moderate", language: "English" },
  { id: 99, title: "The Gifts of Imperfect Parenting", author: "Brene Brown", genre: "non-fiction", mood: ["love", "family", "courage", "healing", "wholehearted living"], description: "Raising children with courage compassion and connection.", summary: "Brene Brown applies her research on wholehearted living to parenting. How to raise children who are resilient compassionate and engaged without sacrificing our own wellbeing.", themes: ["Parenting", "Love", "Courage", "Compassion", "Family"], music: "Norah Jones - Come Away With Me", music_genre: "default", cover_color: "#FCA5A5", year: 2013, pages: 128, reading_time: "3-4 hours", rating: 4.5, difficulty: "easy", language: "English" },
  { id: 100, title: "Crying in H Mart", author: "Michelle Zauner", genre: "memoir", mood: ["grief", "love", "identity", "family", "healing"], description: "A daughter's memoir of losing her Korean mother and holding onto her heritage.", summary: "Michelle Zauner describes losing her mother to cancer and navigating grief through the lens of Korean food and culture. A raw tender meditation on love loss and what we inherit from the people who raised us.", themes: ["Grief", "Love", "Identity", "Food", "Healing"], music: "Max Richter - On the Nature of Daylight", music_genre: "memoir", cover_color: "#FCA5A5", year: 2021, pages: 256, reading_time: "6-7 hours", rating: 4.8, difficulty: "easy", language: "English" },
];

function getBooks(req, res) {
  const { mood, genre, search, difficulty, min_rating, sort, limit } = req.query;
  let filtered = [...books];
  if (mood) filtered = filtered.filter(b => b.mood.some(m => m.toLowerCase().includes(mood.toLowerCase())));
  if (genre) filtered = filtered.filter(b => b.genre.toLowerCase().includes(genre.toLowerCase()));
  if (difficulty) filtered = filtered.filter(b => b.difficulty === difficulty);
  if (min_rating) filtered = filtered.filter(b => b.rating >= parseFloat(min_rating));
  if (search) {
    const q = search.toLowerCase();
    filtered = filtered.filter(b =>
      b.title.toLowerCase().includes(q) ||
      b.author.toLowerCase().includes(q) ||
      b.description.toLowerCase().includes(q) ||
      b.themes.some(t => t.toLowerCase().includes(q)) ||
      b.mood.some(m => m.toLowerCase().includes(q))
    );
  }
  if (sort === 'rating') filtered.sort((a, b) => b.rating - a.rating);
  else if (sort === 'pages_asc') filtered.sort((a, b) => a.pages - b.pages);
  else if (sort === 'pages_desc') filtered.sort((a, b) => b.pages - a.pages);
  else if (sort === 'year') filtered.sort((a, b) => b.year - a.year);
  else if (sort === 'title') filtered.sort((a, b) => a.title.localeCompare(b.title));
  if (limit) filtered = filtered.slice(0, parseInt(limit));
  res.json({ books: filtered, total: filtered.length });
}

function getBookById(req, res) {
  const book = books.find(b => b.id === parseInt(req.params.id));
  if (!book) return res.status(404).json({ error: 'Book not found' });
  res.json(book);
}

function getMoods(req, res) {
  const allMoods = [...new Set(books.flatMap(b => b.mood))].sort();
  const moodCounts = allMoods.map(m => ({ mood: m, count: books.filter(b => b.mood.includes(m)).length }));
  res.json({ moods: allMoods, mood_counts: moodCounts, total: allMoods.length });
}

function getGenres(req, res) {
  const allGenres = [...new Set(books.map(b => b.genre))].sort();
  const genreCounts = allGenres.map(g => ({ genre: g, count: books.filter(b => b.genre === g).length }));
  res.json({ genres: allGenres, genre_counts: genreCounts, total: allGenres.length });
}

function getStats(req, res) {
  res.json({
    total_books: books.length,
    total_moods: [...new Set(books.flatMap(b => b.mood))].length,
    total_genres: [...new Set(books.map(b => b.genre))].length,
    avg_rating: (books.reduce((s, b) => s + b.rating, 0) / books.length).toFixed(2),
    avg_pages: Math.round(books.reduce((s, b) => s + b.pages, 0) / books.length),
    top_rated: [...books].sort((a, b) => b.rating - a.rating).slice(0, 5).map(b => ({ id: b.id, title: b.title, rating: b.rating })),
    quickest_reads: [...books].sort((a, b) => a.pages - b.pages).slice(0, 5).map(b => ({ id: b.id, title: b.title, pages: b.pages })),
  });
}

function getRecommendations(req, res) {
  const { mood, exclude_id, limit = 4 } = req.query;
  let pool = [...books];
  if (mood) pool = pool.filter(b => b.mood.some(m => m.toLowerCase().includes(mood.toLowerCase())));
  if (exclude_id) pool = pool.filter(b => b.id !== parseInt(exclude_id));
  pool.sort(() => Math.random() - 0.5);
  res.json({ books: pool.slice(0, parseInt(limit)), total: pool.length });
}

module.exports = { getBooks, getBookById, getMoods, getGenres, getStats, getRecommendations };
